### ISSUE TITLE
Add related episode segment links and description to the bottoms of auto-generated posts.

### ISSUE THREAD

**Issue by rveitch** [openfcci/fcc-northland-outdoors-radio#25]
### Overview
Add related episode segment links and description to the bottoms of auto-generated posts.

#### Checklist
- [ ] Add links and description for the other two episode segments below the content when posts are generated
- [ ] Add "To find a station near you..." section below the episode segment links
  - Number of stations dynamic?

#### Mockups & Examples
****
**[Segment 1 Example:](http://www.northlandoutdoors.com/2016/02/22/northland-outdoors-radio-podcast-eelpout-vs-sturgeon/)**
![image](https://cloud.githubusercontent.com/assets/12876929/13270414/a28f09be-da53-11e5-8dc5-4c4df5502b2c.png)

Example HTML:
```html
<a href="http://northlandoutdoors.areavoices.com/?p=5554" target="_blank">SEGMENT 2</a>. Jared Olsen explains how the 37th Annual Eelpout Festival came together.

<a href="http://northlandoutdoors.areavoices.com/?p=5558" target="_blank">SEGMENT 3</a>. Chelsea Pettit talks about why Final Approach put a new paint scheme on all their decoys. Also Tim Bogenschutz and Brian Peterson review the new electric fat bike from Rambo.

Northland Outdoors Radio airs on 21 stations across Minnesota, North Dakota and Wisconsin.  To find a station near you, <a href="http://www.northlandoutdoors.com/radio/">visit the “RADIO” page. </a>
```

### Reference
- [Example Post](http://www.northlandoutdoors.com/2016/02/22/northland-outdoors-radio-podcast-eelpout-vs-sturgeon/)

**Comment by jgrinsteinner** [comment]
@rveitch Reminder that this code needs to be reviewed
